### ISSUE TITLE
ACME v2 Compatibility

### ISSUE THREAD

**Issue by EmmanuelAtx** [ridercz/AutoACME#10]
Hi Ridercz,

We need wildcard certificates. Will you implement that?
https://community.letsencrypt.org/t/staging-endpoint-for-acme-v2/49605

**Comment by ridercz** [comment]
Not in the foreseeable future.

According to the [announcement](https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html), it would require DNS authorization, which is waaaaay out of scope for AutoACME. In fact, AutoACME was built explicitly for avoiding DNS authorization. 

They _"may explore additional validation options over time"_. If they'll do some form of HTTP-based authorization, I'll try to implement that.
