### ISSUE TITLE
DNS Challange

### ISSUE THREAD

**Issue by faush01** [ridercz/AutoACME#13]
My ISP blocks port 80 so it looks like I can not use HTTP challenges at all.
Can the tool support DNS challenges?

**Comment by ridercz** [comment]
No, it is waaaaay out of scope for AutoACME. In fact, AutoACME was built explicitly for avoiding the need for DNS authorization. 

There is no universal way to implement DNS challenge. There are various DNS servers and various DNS services and it would be neverending task to implement them all.

**Comment by mactizzle** [comment]
With the wildcard cert being live now, I'm looking for a Windows client that will work. I'd be OK manually adding a DNS TXT rule on initial issuance of the cert. Do you know if the key changes over time? If not, this could be part of your extensive set-up process, then it could still be automated from that point forward.
