### ISSUE TITLE
Instruction for sites that are completely locked out by windows and forms authentication

### ISSUE THREAD

**Issue by AdamHess** [ridercz/AutoACME#15]
The reverse proxy instructions should be updated to handle sites that are completely behind authentication. The /.well-known/ url will not be able to get through with forms and windows auth.

**Comment by ridercz** [comment]
Done [here](https://github.com/ridercz/AutoACME/wiki/Getting-started-with-AutoAcme#authentication-authorization-and-url-rewriting).

**Comment by AdamHess** [comment]
thanks for the quick update, but no suggestions for how to overcome applications that are completely locked at the root level down.

**Comment by ridercz** [comment]
The only way is to modify those applications by adding the exceptions mentioned above.
