### ISSUE TITLE
Wildcard and ACME v2 protocol support

### ISSUE THREAD

**Issue by Tim81** [ridercz/AutoACME#16]
Let's Encrypt Wildcard support as well ACME v2 protocol are live now
https://community.letsencrypt.org/t/acme-v2-and-wildcard-certificate-support-is-live/55579

Can these be added to AutoACME?

**Comment by ridercz** [comment]
Regarding ACMEv2: It will be eventually supported, but it will take time. The entire logic of the Certes library I'm using is changed and it would require extensive changes in AutoACME as well.

For wildcard certs, see FAQ: https://github.com/ridercz/AutoACME/wiki/Feature-FAQ#will-autoacme-support-wildcard-certificates-examplecom
