### ISSUE TITLE
Changes in JSON in LetsEncrypt API - requesting a certificate no longer works 

### ISSUE THREAD

**Issue by janpalas2** [ridercz/AutoACME#2]
Requesting a certificate no longer works because of changes in JSON in LetsEncrypt API - please refer to [this issue](https://github.com/fszlin/certes/issues/5) at Certes project.

The issue has already been resolved, thus the only thing needed to fix the problem in AutoACME is updating Certes NuGet package to version 1.0.7.

**Comment by ridercz** [comment]
Fixed in [1.4.1](https://github.com/ridercz/AutoACME/releases/tag/v1.4.1).
