### ISSUE TITLE
Waiting for authorization......Failed!

### ISSUE THREAD

**Issue by Ajula** [ridercz/AutoACME#21]
Getting bindings from 'localhost'...OK, 3 bindings found
Finding new hosts to add...OK
Accepting TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf...OK
  Adding new host autoacme:
    Testing authorization:
      Writing challenge to C:\InetPub\wwwroot\AutoAcme\probe_593f9cf5-fdeb-4c21-a79c-e74ba0bfb4b6...OK
      Testing HTTP challenge:
        Preparing request to http://autoacme/.well-known/acme-challenge/probe_593f9cf5-fdeb-4c21-a79c-e74ba0bfb4b6...OK
        Getting response...Failed!
        The remote name could not be resolved: 'autoacme'
      Testing HTTPS challenge:
        Preparing request to https://autoacme/.well-known/acme-challenge/probe_593f9cf5-fdeb-4c21-a79c-e74ba0bfb4b6...OK
        Getting response...Failed!
        The remote name could not be resolved: 'autoacme'
      Deleting challenge from C:\InetPub\wwwroot\AutoAcme\probe_593f9cf5-fdeb-4c21-a79c-e74ba0bfb4b6...OK
    Request failed: One or more errors occurred.
  Adding new host www.site.eu:
    Testing authorization:
      Writing challenge to C:\InetPub\wwwroot\AutoAcme\probe_7a750c76-a09c-473e-a8cb-4e4d19e923ee...OK
      Testing HTTP challenge:
        Preparing request to http://www.site.eu/.well-known/acme-challenge/probe_7a750c76-a09c-473e-a8cb-4e4d19e923ee...OK
        Getting response...OK
        Reading response...OK
          OK: Status code 200
          OK: Content-Type header
          OK: Expected response received
      Deleting challenge from C:\InetPub\wwwroot\AutoAcme\probe_7a750c76-a09c-473e-a8cb-4e4d19e923ee...OK
    Getting authorization:
      Creating authorization request...OK, the following is request URI:
      https://acme-v01.api.letsencrypt.org/acme/authz/cK3BTWDh8oNBGPH70u0_6ljPyLcv389ekJwcv2tcoRQ
      Getting challenge...OK, the following is challenge URI:
      https://acme-v01.api.letsencrypt.org/acme/challenge/cK3BTWDh8oNBGPH70u0_6ljPyLcv389ekJwcv2tcoRQ/4075468712
      Writing challenge to C:\InetPub\wwwroot\AutoAcme\q46NE3O0Wj9EuMvo71D2KhV1U_-dtcD43x6AjzWi94A...OK
      Completing challenge...OK
      Waiting for authorization......Failed!
      Last known status: invalid
      Deleting challenge from C:\InetPub\wwwroot\AutoAcme\q46NE3O0Wj9EuMvo71D2KhV1U_-dtcD43x6AjzWi94A...OK
    Request failed: One or more errors occurred.

Where is the problem?

**Comment by ridercz** [comment]
You may only request certificate for FQDN, fully qualified domain name, like `www.something.com`. You're trying to request certificate for one-word intranet name `autoacme` which is a total nonsense, is not supposed to work and never will.

**Comment by Ajula** [comment]
This is FQDN?

C:\CertStore\AutoACME>autoacme addhost www.something.com
Altairis AutoACME Manager version 1.5.4.0
Copyright (c) Michal A. Valasek - Altairis, 2017
www.autoacme.net | www.rider.cz | www.altairis.cz

Reading configuration from 'C:\CertStore\AutoACME\autoacme.json'...OK
Checking host...OK
Requesting cerificate for www.something.com:
Accepting TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf...OK
Testing authorization:
Writing challenge to C:\InetPub\wwwroot\AutoAcme\probe_699917b8-f51a-494e-98fd-8284977de7d4...OK
Testing HTTP challenge:
Preparing request to http://www.something.com/.well-known/acme-challenge/probe_699917b8-f51a-494e-98fd-8284977de7d4...OK
Getting response...OK
Reading response...OK
OK: Status code 200
OK: Content-Type header
OK: Expected response received
Deleting challenge from C:\InetPub\wwwroot\AutoAcme\probe_699917b8-f51a-494e-98fd-8284977de7d4...OK
Getting authorization:
Creating authorization request...OK, the following is request URI:
https://acme-v01.api.letsencrypt.org/acme/authz/aEQ1RF0RxXWp247cTIjcHCGavnPsOR2jICoeGxv59l8
Getting challenge...OK, the following is challenge URI:
https://acme-v01.api.letsencrypt.org/acme/challenge/aEQ1RF0RxXWp247cTIjcHCGavnPsOR2jICoeGxv59l8/4086869370
Writing challenge to C:\InetPub\wwwroot\AutoAcme\rLdpgiMFC9Fh_CXx-y5xkPi5qPm--rvyjwjeseXekOA...OK
Completing challenge...OK
Waiting for authorization.....Failed!
Last known status: invalid
Deleting challenge from C:\InetPub\wwwroot\AutoAcme\rLdpgiMFC9Fh_CXx-y5xkPi5qPm--rvyjwjeseXekOA...OK
Request failed: One or more errors occurred.
Failed!
Unable to get certificate for new host.

**Comment by ridercz** [comment]
Yes, this should work. If it does not, then Let's Encrypt can't access the `http://www.something.com/.well-known/acme-challenge/probe_699917b8-f51a-494e-98fd-8284977de7d4` URL, but AutoACME can. Maybe it's blocked on firewall or something? For getting cert this way the site must be accessible from the Internet, and it isn't.

**Comment by Ajula** [comment]
I've got it. The problem was the AAAA record in DNS pointing elsewhere.

Thank you for your cooperation in solving the problem.

**Comment by ridercz** [comment]
In next version I'll probably add some helpful message for this situation.
