### ISSUE TITLE
Waiting for authorization.....Failed!

### ISSUE THREAD

**Issue by giacinto41** [ridercz/AutoACME#28]
Hi,

I am having some problems with getting this certificate installed. We are trying to implement DirectAccess 
and so we need to install public ssl certificates to make this work. I have a public domain (da.voltechrebuilders.com) pointing to my corporate network public IP (A and AAAA record pointing to my IP4 and IP6 address respectively), which is then forwarded to the web server on my network . I can reach the IIS default site from the internet just fine. Since we are doing this to deploy DirectAccess we don't have an actual website and so I am doing all this with the default website. 

Here is my attempt at getting a certificate (trying multiple times, always the same result):

C:\CertStore\AutoACME>autoacme addhost da.voltechrebuilders.com
Altairis AutoACME Manager version 1.5.4.0
Copyright (c) Michal A. Valasek - Altairis, 2017
www.autoacme.net | www.rider.cz | www.altairis.cz

Reading configuration from 'C:\CertStore\AutoACME\autoacme.json'...OK
Checking host...OK
Requesting cerificate for da.voltechrebuilders.com:
  Accepting TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf...OK
  Testing authorization:
    Writing challenge to C:\InetPub\wwwroot\AutoAcme\probe_032d6b95-b1af-4eef-a88e-2abefdbd3bdd...OK
    Testing HTTP challenge:
      Preparing request to http://da.voltechrebuilders.com/.well-known/acme-challenge/probe_032d6b95-b1af-4eef-a88e-2abefdbd3bdd...OK
      Getting response...OK
      Reading response...OK
        OK: Status code 200
        OK: Content-Type header
        OK: Expected response received
    Deleting challenge from C:\InetPub\wwwroot\AutoAcme\probe_032d6b95-b1af-4eef-a88e-2abefdbd3bdd...OK
  Getting authorization:
    Creating authorization request...OK, the following is request URI:
    https://acme-v01.api.letsencrypt.org/acme/authz/Wy7pKIOTpJiEm1ZaOEW6NX9c-8xTEz6okf6AAFacNAo
    Getting challenge...OK, the following is challenge URI:
    https://acme-v01.api.letsencrypt.org/acme/challenge/Wy7pKIOTpJiEm1ZaOEW6NX9c-8xTEz6okf6AAFacNAo/6292277342
    Writing challenge to C:\InetPub\wwwroot\AutoAcme\KYJ5xdpeJMVC4-Vu6s_CNLlS6RmkUMMHaVb_WgguCjo...OK
    Completing challenge...OK
    Waiting for authorization.....Failed!
    Last known status: invalid
    Deleting challenge from C:\InetPub\wwwroot\AutoAcme\KYJ5xdpeJMVC4-Vu6s_CNLlS6RmkUMMHaVb_WgguCjo...OK
  Request failed: One or more errors occurred.
  Failed!
  Unable to get certificate for new host.

Can anyone help, I am at a loss!!!

**Comment by giacinto41** [comment]
Hi,

I did a bit more testing and I think that my ISP is blocking port 80 for incoming connections. I have been testing from another LAN (different seperate VLAN but behind the same Router) thinking that when the site resolved everything was working.

Im assuming that there isn't another port that I could get the request from?? Ill be contacting my ISP today to confirm whether they are blocking the port and if I can open it.

Thanks

**Comment by ridercz** [comment]
For HTTP verification your site needs to be reachable on port 80 (HTTP) or 443 (HTTPS). It's intentional and there is no workaround.

**Comment by ridercz** [comment]
See also [#11]
