### ISSUE TITLE
Waiting for authorization....Failed!

### ISSUE THREAD

**Issue by juanonsoftware** [ridercz/AutoACME#30]
Hello,
Can we know the detail of this error : "Waiting for authorization....Failed!" ?
Below is the output I've run. Thanks !

---

Checking host...OK
Requesting cerificate for www.devcovery.com:
  Accepting TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf...OK
  Testing authorization:
    Writing challenge to C:\InetPub\wwwroot\AutoAcme\probe_2444acea-4aba-4748-bb29-dd4513ebaa93...OK
    Testing HTTP challenge:
      Preparing request to http://www.devcovery.com/.well-known/acme-challenge/probe_2444acea-4aba-4748-bb29-dd4513ebaa9
3...OK
      Getting response...OK
      Reading response...OK
        OK: Status code 200
        OK: Content-Type header
        OK: Expected response received
    Deleting challenge from C:\InetPub\wwwroot\AutoAcme\probe_2444acea-4aba-4748-bb29-dd4513ebaa93...OK
  Getting authorization:
    Creating authorization request...OK, the following is request URI:
    https://acme-v01.api.letsencrypt.org/acme/authz/mSXykXd5FYIp-2vLIgr5yzp6YYQv25Ox2Sx53faB1mU
    Getting challenge...OK, the following is challenge URI:
    https://acme-v01.api.letsencrypt.org/acme/challenge/mSXykXd5FYIp-2vLIgr5yzp6YYQv25Ox2Sx53faB1mU/8805082239
    Writing challenge to C:\InetPub\wwwroot\AutoAcme\ValhBgOmhYL_EO1zyarO0-DGs80BZyRQ8zmIY3-hzX8...OK
    Completing challenge...OK
    Waiting for authorization....Failed!
    Last known status: invalid
    Deleting challenge from C:\InetPub\wwwroot\AutoAcme\ValhBgOmhYL_EO1zyarO0-DGs80BZyRQ8zmIY3-hzX8...OK
  Request failed: One or more errors occurred.
  Failed!
  Unable to get certificate for new host.

**Comment by avonwyss** [comment]
If you run the command with `--verbose` you might get more details. However, this looks very much like #28 - is the `www.devcovery.com` site correctly reachable from the internet (e.g. no URL filtering or so)?

**Comment by juanonsoftware** [comment]
yes it might be my issue on url rewrite, it's now working [www.devcovery.com](https://www.devcovery.com) . Thanks for the great work !
