### ISSUE TITLE
Version 1.6 error loading System.Net.HTTP

### ISSUE THREAD

**Issue by DerKamii** [ridercz/AutoACME#37]
Hi,

your release has a problem with System.Net.Http:
Could not load file or assembly 'System.Net.Http, Version=4.2.0.0

Full Msg:
Unbehandelte Ausnahme: System.IO.FileLoadException: Die Datei oder Assembly "System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
   bei Altairis.AutoAcme.Core.AutoAcmeContext..ctor(Uri serverAddress)
   bei Altairis.AutoAcme.Manager.Program.InitCfg(Boolean useDefaults, String cfgFileName, Boolean overwrite, Boolean verbose)
   bei lambda_method(Closure , Object , Object[] )
   bei NConsoler.Consolery.InvokeMethod(MethodInfo method)
   bei NConsoler.Consolery.RunAction()
   bei NConsoler.Consolery.Run(Type targetType, String[] args, IMessenger messenger, Notation notationType)
   bei NConsoler.Consolery.Run()
   bei Altairis.AutoAcme.Manager.Program.Main(String[] args)

1.5.4 still work's great.

**Comment by avonwyss** [comment]
@DerKamii Thanks for reporting. You can fix this by editing the `.config` file. The assembly redirect for System.Net.Http should be like this:
```
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.1.1.3" />
      </dependentAssembly>
```
@ridercz The nuget package update https://github.com/ridercz/AutoACME/commit/9d2732427419f6d0761a7c750e7cd6b0f6f9964a broke this, I fixed the `.config` files, could you make another release?

**Comment by ridercz** [comment]
Fixed in 1.6.1.
