### ISSUE TITLE
Unable to connect to the remote server

### ISSUE THREAD

**Issue by vankampenp** [ridercz/AutoACME#42]
On a server where everything worked fine before, I am now getting errors:.
Getting response...Failed
Unable to connect to the remote server

I inserted a test.txt in c:\InetPub\wwwroot\AutoAcme and can download it as http://localhost/AutoAcme/test.txt (locally)
and
as
http://<mydomain>/.well-known/acme-challenge/test.txt (from other locations)
The same for the probe documents that appear when written in the C:\inetpub\wwwroot\AutoACME

My certificates are due to expire at the end of next week. I would appreciate any help to debug what's wrong.
Pieter

**Comment by ridercz** [comment]
Please post entire output.

**Comment by vankampenp** [comment]
Altairis AutoACME Manager version 1.5.1.0
Copyright (c) Michal A. Valasek - Altairis, 2017
www.autoacme.net | www.rider.cz | www.altairis.cz

Reading configuration from 'C:\CertStore\autoAcme\autoacme.json'...OK
Loading hosts expiring in 30 days...OK, 6 hosts to renew
Accepting TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf...OK
Host nl.managetests.nl expires in 5 days (zondag 7 juli 2019)
  Testing authorization:
    Writing challenge to C:\InetPub\wwwroot\AutoAcme\probe_20660f5d-af55-4edb-9292-be4fff8567ce...OK
    Testing HTTP challenge:
      Preparing request to http://nl.managetests.nl/.well-known/acme-challenge/probe_20660f5d-af55-4edb-9292-be4fff8567ce...OK
      Getting response...Failed!
      Unable to connect to the remote server
    Testing HTTPS challenge:
      Preparing request to http://nl.managetests.nl/.well-known/acme-challenge/probe_20660f5d-af55-4edb-9292-be4fff8567ce...OK
      Getting response...Failed!
      Unable to connect to the remote server
    Deleting challenge from C:\InetPub\wwwroot\AutoAcme\probe_20660f5d-af55-4edb-9292-be4fff8567ce...OK
  Renewal failed: One or more errors occurred.

The other 5 have the same output. I have put a test file in the probe location (C:\inetpub\wwwroot\AutoACME)
http://nl.managetests.nl/.well-known/acme-challenge/test.txt

**Comment by avonwyss** [comment]
You're using an old version (1.5.1), have you tried an updated one? You may for instance be affected by issue #12 (just guessing...).

**Comment by vankampenp** [comment]
Thanks, I updated, and now the https challenge actually goes to the https address, but it still fails unfortunately

**Comment by ridercz** [comment]
The server `nl.managetests.nl` is unreachable both to AutoACME and to me right now, therefore also for the Let's Encrypt servers. AutoACME is right. Your server must be publicly reachable and it is not.

**Comment by vankampenp** [comment]
@ridercz Hi, can you please check again? It must have been while I was trying some stuff. I can reach the sites from gtmetrix (and from my mobile network).

**Comment by vankampenp** [comment]
@ridercz Just found out that Certify the Web is able to renew the certificates. So there must be an issue with my configuration of AutoAcme.

**Comment by ridercz** [comment]
According to the log you posted the server was unable to download the probe. At the time I tested it, I was also unable to connect to the server. So I think there wasn't problem with configuration of AutoACME, but with your server.

With default settings, AutoACME will try to check if the probe is available, before requesting the check by Let's Encrypt servers. So the probe URL has to be accessible both from the Internet and from the server itself, using the external address. In some setup, it may be a problem, with split DNS etc. 

You can disable the test with the `/xt` command line switch. If used, AutoACME won't test the URL and will call directly Let's Encrypt servers.

**Comment by vankampenp** [comment]
With /xt it works. For some reason, the external address is not reachable from the server, I will look in to that further, but for now I have the certificates. 
The message "Unable to connect to the remote server" did not give me the hint that this was about the external address of the local server. 
Thanks a lot for your help and for the great tool.
