### ISSUE TITLE
Certificate renewal failure - Completing challenge...Challenge Invalid

### ISSUE THREAD

**Issue by AnthonyBe** [ridercz/AutoACME#43]
I've been using AutoACME for over a year without a hitch on my Windows Server 2012 R2 server. In the last week, I just noticed my certificate wasn't successfully renewing.

When I run 'autoacme maintenance' I'm getting the following:

```
Altairis AutoACME Manager version 1.6.2.0
Copyright ¸ Michal A. Val sek - Altairis and contributors, 2017-2019
www.autoacme.net | www.rider.cz | www.altairis.cz

Reading configuration from 'C:\Scripts\CertStore\AutoACME\autoacme.json'...OK
Loading hosts expiring in 30 days...OK, 1 hosts to renew
Accepting TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf...OK
Host anthonyb.no-ip.biz expires in 19 days (Sunday, 25 August 2019)
  Testing authorization:
    Writing challenge to C:\InetPub\wwwroot\AutoAcme\probe_dc8e482f-4a21-485e-9687-3247228eebe8...OK
    Testing HTTP challenge:
      Preparing request to http://anthonyb.no-ip.biz/.well-known/acme-challenge/probe_dc8e482f-4a21-485e-9687-3247228eebe8...OK
      Getting response...OK
      Reading response...OK
        OK: Status code 200
        OK: Content-Type header
        OK: Expected response received
    Deleting challenge from C:\InetPub\wwwroot\AutoAcme\probe_dc8e482f-4a21-485e-9687-3247228eebe8...OK
  Preparing order
  Getting authorization:
    Getting challenge...
      OK, the following is DNS name:
        anthonyb.no-ip.biz
        Writing challenge to C:\InetPub\wwwroot\AutoAcme\1qnCEm31-vSaOZUavBIggk7-eMWem3Vb9iTbtJyUSuE...OK
    Completing challenge...Challenge Invalid: https://acme-v02.api.letsencrypt.org/acme/challenge/1kh_4_oKzQpx5Xxk2h10hl5Nx7hevYHh_GEu09sqBF0/19176569488 Fetching http://anthonyb.no-ip.biz/.well-known/acme-challenge/1qnCEm31-vSaOZUavBIggk7-eMWem3Vb9iTbtJyUSuE: Timeout during connect (likely firewall problem)
    Failed
    Deleting challenge from C:\InetPub\wwwroot\AutoAcme\1qnCEm31-vSaOZUavBIggk7-eMWem3Vb9iTbtJyUSuE...OK
  Renewal failed!
  Authorization failed with status False
Loading hosts expired at least 30 days ago...OK, no hosts to purge
```
I'm not aware of any config change on my side in the last 1-2 months.
Any suggestions on what might be causing my issue?

Many thanks in advance!

**Comment by avonwyss** [comment]
@AnthonyBe I also get a timeout when accessing `anthonyb.no-ip.biz` so your host is apparently not accessible from the internet. If this is because of firewall rules you have, please do note that the IPs used by Let's Encrypt may change without notification, since [they do not publish a list of IPs](https://letsencrypt.org/docs/faq/#what-ip-addresses-does-let-s-encrypt-use-to-validate-my-web-server).

This is not a problem of AutoACME, so I'm closing this issue.

**Comment by AnthonyBe** [comment]
Apologies, it seems that a recent plan change with my ISP had resulted in ports 80 and 443 being blocked. I hadn't noticed as the URLs work from home (i.e. the ports aren't blocked inside the ISP's network).

I'll contact my ISP to rectify.
