### ISSUE TITLE
Upgrade instructions: ACMEv1 to ACMEv2?

### ISSUE THREAD

**Issue by chagrawil** [ridercz/AutoACME#46]
Is there a recommended upgrade path? More specifically, going from an ACMEv1 version to 1.6.2.0 for ACMEv2, are changes needed to the json files to enable or force v2?

**Comment by avonwyss** [comment]
No, it should just work transparently. On the first request the new version of AutoACME will migrate the account to v2.

**Comment by carloslealxyzt** [comment]
Hi, What I have to do to make the upgrade from ACMEv1 to ACMEv2? Just change the "ServerUri" in the "autoacme.json" file is enough? Is there any upgrade instructions?

**Comment by avonwyss** [comment]
@carloslealxyzt It does that automatically if you're using the well-known LE servers, see https://github.com/ridercz/AutoACME/blob/0b4864e4d486e2455c6f4405a3816a6f62c58ce9/Altairis.AutoAcme.Core/AutoAcmeContext.cs#L20-L25

**Comment by carloslealxyzt** [comment]
Hi @avonwyss, thanks for your response, I'm using AutoACME 1.5.4, and I think that I'm still using ACMEv1, because when I renew a domain, I get the e-mail to update.

**Comment by avonwyss** [comment]
@carloslealxyzt V1.6.0 is the first to use ACMEv2 AFAIR.

**Comment by carloslealxyzt** [comment]
Hi @avonwyss thanks for your response, is there any upgrade instructions? How should I do?

**Comment by avonwyss** [comment]
@carloslealxyzt Make a backup of your files just in case, then replace the old version with the new version. You can then test it from the command line.

**Comment by RyanDansie** [comment]
Here's how i did it:
1. Download the file AutoACME-1.6.2.zip from https://github.com/ridercz/AutoACME/releases/tag/v1.6.2
2. Extract the zip file on the server. On my system the existing installation was on a path like C:\...\AutoAcme-1.5.1 so the new version was unzipped to C:\...\AutoAcme-1.6.2
3. Copied the autoacme.json and autoacme.json.old files from the old installation folder to the new one
4. Updated my task scheduler job to the file path for the new version exe (could also rename the folders so the new version was on the same path as the old one)
