### ISSUE TITLE
Not working with some application

### ISSUE THREAD

**Issue by CPZbre** [ridercz/AutoACME#5]
Hi !

I'm try your solution but the URL rewriting does not work whit all applications.

With [proget](https://inedo.com/proget) from Inedo the url rewrite is succesfull processing but the application still return 404.

**Comment by ridercz** [comment]
Sadly, the URL rewriting really does not work under absolutely all circumstances. If application does its own rewriting or processing before it is supposed to, there is nothing AutoACME can do.

I recommend you to solve this issue with Proget and tell them to simply ignore all requests to `/.well-known/acme-challenge/*`. Maybe it can be even configured somewhere?

**Comment by lfurzewaddock** [comment]
Having the same problem with SmarterMail by SmarterTools, which supposedly does support Let's Encrypt, but not this implementation its seems.

Easiest manual workaround is to stop the site in IIS, run AutoACME, then start the site in IIS.
